#!/bin/sh
ssh ubuntu@13.125.231.250 <<EOF
    cd ~/jenkins_test
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install 16.2.0
    npm install npm
    npm install -g pm2
    pm2 restart app.js
    exit
EO